# Generated by Django 5.2.1 on 2025-05-21 20:32

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("portfolio", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="languageproficiency",
            options={
                "verbose_name": "Language Proficiency",
                "verbose_name_plural": "Language Proficiencies",
            },
        ),
        migrations.AlterModelOptions(
            name="skillcategory",
            options={
                "verbose_name": "Skill Category",
                "verbose_name_plural": "Skill Categories",
            },
        ),
    ]
