# Generated by Django 5.2.1 on 2025-05-28 23:01

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("portfolio", "0002_alter_languageproficiency_options_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="project",
            name="media",
            field=models.FileField(
                blank=True,
                null=True,
                upload_to="media/projects",
                validators=[
                    django.core.validators.FileExtensionValidator(
                        allowed_extensions=["jpg", "jpeg", "png", "gif", "mp4", "mov"]
                    )
                ],
            ),
        ),
    ]
