# Generated by Django 5.2.1 on 2025-05-29 04:39

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("portfolio", "0003_project_media"),
    ]

    operations = [
        migrations.AlterField(
            model_name="project",
            name="media",
            field=models.FileField(
                blank=True,
                null=True,
                upload_to="projects",
                validators=[
                    django.core.validators.FileExtensionValidator(
                        allowed_extensions=["jpg", "jpeg", "png", "gif", "mp4", "mov"]
                    )
                ],
            ),
        ),
    ]
