# Generated by Django 5.2.1 on 2025-06-06 11:28

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("portfolio", "0004_alter_project_media"),
    ]

    operations = [
        migrations.AddField(
            model_name="skill",
            name="icon",
            field=models.CharField(
                blank=True,
                help_text="Class Font Awesome (ex: 'fab fa-python', 'fas fa-database')",
                max_length=100,
            ),
        ),
    ]
