# Generated by Django 5.2.1 on 2025-06-06 13:41

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("portfolio", "0005_skill_icon"),
    ]

    operations = [
        migrations.AddField(
            model_name="education",
            name="diploma",
            field=models.FileField(
                blank=True,
                help_text="Diploma document (PDF)",
                null=True,
                upload_to="medias/diplomas",
                validators=[django.core.validators.FileExtensionValidator(["pdf"])],
            ),
        ),
        migrations.AddField(
            model_name="education",
            name="logo",
            field=models.ImageField(
                blank=True,
                help_text="Logo of the institution",
                null=True,
                upload_to="medias/education/logos",
            ),
        ),
        migrations.CreateModel(
            name="Transcript",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "label",
                    models.CharField(
                        help_text="e.g. 'Semestre 1', 'Final transcript'",
                        max_length=255,
                    ),
                ),
                (
                    "file",
                    models.FileField(
                        help_text="Transcript file in PDF",
                        upload_to="medias/transcripts/",
                        validators=[
                            django.core.validators.FileExtensionValidator(["pdf"])
                        ],
                    ),
                ),
                ("uploaded_at", models.DateTimeField(auto_now_add=True)),
                (
                    "education",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="transcripts",
                        to="portfolio.education",
                    ),
                ),
            ],
        ),
    ]
