# Generated by Django 5.2.1 on 2025-06-06 13:48

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("portfolio", "0006_education_diploma_education_logo_transcript"),
    ]

    operations = [
        migrations.AlterField(
            model_name="education",
            name="logo",
            field=models.ImageField(
                blank=True,
                help_text="Logo of the institution",
                null=True,
                upload_to="medias/logos",
            ),
        ),
    ]
