# Generated by Django 5.2.1 on 2025-06-06 15:06

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("portfolio", "0007_alter_education_logo"),
    ]

    operations = [
        migrations.AddField(
            model_name="certification",
            name="is_primary",
            field=models.BooleanField(
                default=False, help_text="Mark as main certification"
            ),
        ),
        migrations.AddField(
            model_name="certification",
            name="pdf",
            field=models.FileField(
                blank=True,
                null=True,
                upload_to="medias/certifications/",
                validators=[django.core.validators.FileExtensionValidator(["pdf"])],
            ),
        ),
    ]
